# Generated by Django 3.0.5 on 2024-07-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240731_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminnotice',
            old_name='date1',
            new_name='ndate1',
        ),
    ]
