# Generated by Django 3.0.5 on 2024-08-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240731_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotice',
            name='ndate1',
            field=models.CharField(max_length=20),
        ),
    ]
